# Generated by Django 4.0.2 on 2022-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img_url',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
