# Generated by Django 4.0.2 on 2022-02-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_img_url_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='img_url',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
    ]
